name: 'Robocorp - Trigger Cloud process'
description: 'Trigger a Robocorp Cloud process'
inputs:
  api-key:
    description: 'Workspace API key'
    required: true
  workspace-id:
    description: 'Target Robocorp Cloud worskpace ID'
    required: true
  process-id:
    description: 'Target Robocorp Cloud process ID'
    required: true
  payload:
    description: JSON payload for the robot
  await-complete:
    description: Should the action wait for process completion
  timeout:
    description: Max time to wait for the action to complete (in seconds)
    default: '120'
  api-endpoint:
    description: Robocorp workspace API endpoint
    default: https://api.eu1.robocloud.eu/process-v1
runs:
  using: 'node12'
  main: 'dist/index.js'
