name: Test action

on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Run action tests
    steps:
      - name: Trigger Robocorp Cloud process
        uses: ./
        with:
          process-secret: ${{ secrets.ROBOCORP_SECRET }}
          process-url: ${{ secrets.ROBOCORP_URL }}
          payload: '{"term":"cute dog picture"}'
          await-complete: true
