name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Run code tests
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn build
      - name: Run action tests
        uses: ./
        with:
          process-secret: ${{ secrets.ROBOCORP_SECRET }}
          process-url: ${{ secrets.ROBOCORP_URL }}
          payload: '{"term":"cute dog picture"}'
          await-complete: true
